version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amrutam-backend
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./best_efficientnet.pth:/app/best_efficientnet.pth
    command: python app.py

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: amrutam-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: npm run dev

