[build]
  # Directory to change to before starting a build
  base = "amrutam-ai"
  
  # Next.js on Netlify publishes the ".next" output
  publish = ".next"
  
  # Default build command
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.11.0"

# Next.js handles routes; no SPA catch-all redirect needed

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Enable Netlify Next.js runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"
