services:
  - type: web
    name: amrutam-backend
    env: python
    region: oregon
    plan: free
    rootDir: .
    buildCommand: git lfs install && git lfs pull && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /health
    disk:
      name: model-cache
      mountPath: /app
      sizeGB: 2
